default:
  image: node:20.12.2-bookworm
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .npm

stages:
  - build
  - deploy

create-archive:
  stage: build
  script:
    - echo "Downloading dependencies"
    - npm ci --cache .npm
    - echo "Creating archive"
    - tar --exclude='.*' -czf website.tar.gz *
  artifacts:
    paths:
      - website.tar.gz

deploy-staging:
  stage: deploy
  environment: staging
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  script:
    - chmod 600 ${SSH_KEY}
    - scp -i ${SSH_KEY} -o StrictHostKeyChecking=no -o "PubkeyAcceptedAlgorithms=+ssh-rsa" website.tar.gz ${SSH_USER}@${SSH_HOST}:/opt/website/website.tar.gz
    - ssh -i ${SSH_KEY} -o StrictHostKeyChecking=no -o "PubkeyAcceptedAlgorithms=+ssh-rsa" ${SSH_USER}@${SSH_HOST} "cd /opt/website && ./deploy.sh"

deploy-production-yoso-fi:
  stage: deploy
  environment: production yoso.fi
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - chmod 600 ${SSH_KEY}
    - scp -i ${SSH_KEY} -o StrictHostKeyChecking=no website.tar.gz ${SSH_USER}@${SSH_HOST}:/home/${SSH_USER}/website.tar.gz
    - ssh -i ${SSH_KEY} -o StrictHostKeyChecking=no ${SSH_USER}@${SSH_HOST} /home/${SSH_USER}/deploy.sh

deploy-production-yczech-cz:
  stage: deploy
  environment: production yczech.cz
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - chmod 600 ${SSH_KEY}
    - scp -i ${SSH_KEY} -o StrictHostKeyChecking=no website.tar.gz ${SSH_USER}@${SSH_HOST}:/home/${SSH_USER}/website.tar.gz
    - ssh -i ${SSH_KEY} -o StrictHostKeyChecking=no ${SSH_USER}@${SSH_HOST} /home/${SSH_USER}/deploy.sh
