default:
  image: node:20.12.2-bookworm
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .npm

stages:
  - build
  - deploy

create-archive:
  stage: build
  script:
    - echo "Downloading dependencies"
    - npm ci --cache .npm
    - echo "Creating archive"
    - tar --exclude='.*' -czf website.tar.gz * 
  artifacts:
    paths:
      - website.tar.gz

deploy:
  stage: deploy
  environment: staging
  script:
    - chmod 600 ${SSH_KEY}
    - scp -i ${SSH_KEY} -o StrictHostKeyChecking=no -o "PubkeyAcceptedAlgorithms=+ssh-rsa" website.tar.gz ${SSH_USER}@${SSH_HOST}:/opt/website/website.tar.gz
    - ssh -i ${SSH_KEY} -o StrictHostKeyChecking=no -o "PubkeyAcceptedAlgorithms=+ssh-rsa" ${SSH_USER}@${SSH_HOST} "cd /opt/website && ./deploy.sh"
